"added my settings
"Disable automatic comment insertion
autocmd FileType * setlocal formatoptions-=ro
"for full-width symbol
set ambiwidth=double
"Converting tabs to 2spaces
set tabstop=2 shiftwidth=2 expandtab
highlight Comment ctermfg=lightblue
