"added my settings
"Disable automatic comment insertion
autocmd FileType * setlocal formatoptions-=ro
"for full-width symbol
set ambiwidth=double
highlight Comment ctermfg=lightblue
set enc=utf-8
set paste
set hlsearch

"Move to last position
augroup vimrcEx
  au BufRead * if line("'\"") > 0 && line("'\"") <= line("$") |
  \ exe "normal g`\"" | endif
augroup END

"autocmd BufRead,BufNewFile *.py setfiletype python
"autocmd BufRead,BufNewFile *.rb setfiletype ruby
"autocmd BufRead,BufNewFile *.sh setfiletype sh
"autocmd BufRead,BufNewFile *.php setfiletype php

set tabstop=2 shiftwidth=2 expandtab
