let OSTYPE = system('uname')
if OSTYPE == "Darwin\n"
  :set term=xterm-256color
  :syntax on
endif

augroup vimrcEx
  au BufRead * if line("'\"") > 0 && line("'\"") <= line("$") |
  \ exe "normal g`\"" | endif
augroup END

autocmd FileType * setlocal formatoptions-=ro
set ambiwidth=double
highlight Comment ctermfg=lightblue
set enc=utf-8
set paste
set hlsearch

set tabstop=2 shiftwidth=2 expandtab


"added my settings
